**Numpay:**

Arrays multidimensionais (ndarrays):
Núcleo do NumPy, para dados numéricos eficientes.
Funções matemáticas:
Ampla gama para operações em arrays.
Alto desempenho:
Implementação em C para cálculos rápidos.
Base para outras bibliotecas:
Fundamental em ciência de dados e aprendizado de máquina.
Essencial para computação numérica:
Ferramenta chave para análise e manipulação de dados.

**PANDAS**


Estruturas de dados:
DataFrame: tabelas para dados organizados.
Series: colunas de dados.
Facilidade de uso:
Leitura e escrita de dados em vários formatos (CSV, Excel, etc.).
Ferramentas para limpar e organizar dados.
Poder de análise:
Cálculos estatísticos e exploração de dados.
Integração com outras bibliotecas para visualização.

In [14]:
import numpy as np
import pandas as pd

In [15]:
serie = pd.Series(np.random.random(5), name = "Coluna 01")
  ### Gera 5 números aleatórios no intervalo [0, 1) ###

In [16]:
serie

0    0.005730
1    0.474811
2    0.446224
3    0.307088
4    0.482963
Name: Coluna 01, dtype: float64

In [17]:
serie[3]

np.float64(0.3070880956493043)

In [18]:
print(round(serie[3], 2))

0.31

In [19]:
import yfinance as yf

PG = yf.download('PG', start='2026-01-01')
###PG (Procter & Gamble) ###

[*********************100%***********************]  1 of 1 completed

ticker é um código único usado para identificar uma ação, fundo ou outro ativo financeiro negociado em bolsa. No nosso caso, PG é o ticker da Procter & Gamble na Bolsa de Valores de Nova York (NYSE).

Date - Data do pregão.

Close - Preço de fechamento da ação no dia.

High - Maior preço alcançado pela ação no dia.

Low - Menor preço alcançado pela ação no dia.

Open - Preço de abertura da ação no dia.

Volume - Número total de ações negociadas no dia.

In [20]:
PG

Price            Close        High         Low        Open    Volume
Ticker              PG          PG          PG          PG        PG
Date
2026-01-02  138.702728  140.218982  138.164716  139.993994   8946100
2026-01-05  137.313644  138.272317  136.560421  138.027760  12297300
2026-01-06  136.863678  138.340795  136.472378  137.333223  10421800
2026-01-07  135.034393  136.756082  134.623540  136.756082  14369100
2026-01-08  138.448380  138.692936  134.819168  134.887636   9297100
...                ...         ...         ...         ...       ...
2026-09-03  146.919998  148.220001  146.500000  147.679993   6105800
2026-09-04  146.440002  147.149994  145.820007  146.470001   5588200
2026-09-08  145.580002  146.160004  144.300003  145.600006   8325100
2026-09-09  142.639999  144.470001  142.339996  144.160004   9270000
2026-09-10  142.970001  143.509995  141.860001  142.600006  10893968

[173 rows x 5 columns]

In [21]:
PG.tail()

Price            Close        High         Low        Open    Volume
Ticker              PG          PG          PG          PG        PG
Date
2026-09-03  146.919998  148.220001  146.500000  147.679993   6105800
2026-09-04  146.440002  147.149994  145.820007  146.470001   5588200
2026-09-08  145.580002  146.160004  144.300003  145.600006   8325100
2026-09-09  142.639999  144.470001  142.339996  144.160004   9270000
2026-09-10  142.970001  143.509995  141.860001  142.600006  10893968

In [22]:
PG.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 173 entries, 2026-01-02 to 2026-09-10
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   (Close, PG)   173 non-null    float64
 1   (High, PG)    173 non-null    float64
 2   (Low, PG)     173 non-null    float64
 3   (Open, PG)    173 non-null    float64
 4   (Volume, PG)  173 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 8.1 KB

In [23]:
tickers = ['PG', 'MSFT', 'T', 'F', 'GE'] #lista de ações

In [24]:
new_data = pd.DataFrame()

In [25]:
inicio = '2026-01-01'
fim = '2026-09-10'

In [26]:
new_data = yf.download(tickers, start=inicio, end=fim)['Close']

[*********************100%***********************]  4 of 5 completed

In [28]:
new_data

Ticker              F          GE        MSFT          PG          T
Date
2026-01-02  12.893155  319.884705  469.958496  138.702744  23.706533
2026-01-05  13.018801  323.445099  469.869110  137.313644  23.851318
2026-01-06  13.337747  326.656372  475.493408  136.863663  23.494177
2026-01-07  13.279757  322.766907  480.422119  135.034378  23.137035
2026-01-08  13.917649  313.591736  475.095886  138.448395  23.330084
...               ...         ...         ...         ...        ...
2026-09-02  14.140000  329.500000  496.820007  147.639999  25.950001
2026-09-03  14.410000  333.480011  510.119995  146.919998  26.190001
2026-09-04  14.620000  337.119995  499.700012  146.440002  25.680000
2026-09-08  14.000000  334.910004  493.950012  145.580002  25.600000
2026-09-09  13.450000  325.420013  491.649994  142.639999  25.150000

[172 rows x 5 columns]